
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    mem_limit: 5g 
    environment:
      - RAG_HOST=rag.oulcaid.tech
  
  chroma:
    image: chromadb/chroma:0.4.24
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d

  backend:
    build: rag
    image: back:rag
    container_name: back
    ports:
      - "8080:8080"

  frontend:
    build: client
    image: front:rag
    container_name: front
    ports:
      - "443:443"
    volumes:
      - mongo-data:/data/db
      
volumes:
  ollama-data:
  chroma-data:
  mongo-data:
