
services:
  frontend:
    build: client
    image: rag-app-frontend:1.1
    container_name: front
    ports:
      - "443:443"
    volumes:
      - ./client/logs:/etc/nginx/logs
    environment:
      - RAG_HOST=rag.oulcaid.tech

  backend:
    build: rag
    image: back:rag
    container_name: back
    ports:
      - "8080:8080"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    mem_limit: 5g 
    environment:
      - RAG_HOST=rag.oulcaid.tech
  
  chroma:
    image: chromadb/chroma:0.4.24
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    env_file: 
      - ./prometheus/.env
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
      - ./grafana/.env
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      
volumes:
  ollama-data:
  chroma-data:
  mongo-data:
  grafana-data:


