
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    mem_limit: 5g 
  
  chroma:
    image: chromadb/chroma:0.4.24
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma

  # openui:
  #   image: openui/openui
  #   environment:
  #     - API_HOST=http://ollama:11434
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - ollama

volumes:
  ollama-data:
  chroma-data: